package com.smartstay.console.responses.orderHistory;

import com.smartstay.console.responses.hostels.OwnerInfo;

public record OrderHistoryResponse(Long historyId,
                                   String hostelId,
                                   String hostelName,
                                   String hostelInitials,
                                   String hostelType,
                                   String mobile,
                                   String houseNo,
                                   String street,
                                   String landmark,
                                   String city,
                                   String state,
                                   int country,
                                   int pincode,
                                   String fullAddress,
                                   String mainImage,
                                   OwnerInfo ownerInfo,
                                   Double discountAmount,
                                   Double planAmount,
                                   String planCode,
                                   String planName,
                                   String planType,
                                   Double totalAmount,
                                   String orderStatus,
                                   String paymentType,
                                   String channel,
                                   String paymentProof,
                                   String paymentProofFileName,
                                   String upiId,
                                   String cardHolderName,
                                   String cardType,
                                   String cardBrand,
                                   String cardIssuer,
                                   String cardNo,
                                   String userType,
                                   String paidBy,
                                   String collectedBy,
                                   String createdBy,
                                   String createdAtDate,
                                   String createdAtTime) {
}
