package com.smartstay.console.responses.orderHistory;

public record OrderHistoryResponse(Long historyId,
                                   String hostelId,
                                   String hostelName,
                                   String hostelInitials,
                                   String hostelType,
                                   String mobile,
                                   String houseNo,
                                   String street,
                                   String landmark,
                                   String city,
                                   String state,
                                   int country,
                                   int pincode,
                                   String fullAddress,
                                   String mainImage,
                                   Double discountAmount,
                                   Double planAmount,
                                   String planCode,
                                   String planName,
                                   String planType,
                                   Double totalAmount,
                                   String orderStatus,
                                   String paymentType,
                                   String channel,
                                   String upiId,
                                   String cardHolderName,
                                   String cardType,
                                   String cardBrand,
                                   String cardIssuer,
                                   String cardNo,
                                   String userType,
                                   String createdBy,
                                   String createdAtDate,
                                   String createdAtTime) {
}
