package com.smartstay.console.responses.hostels;

import com.smartstay.console.responses.bills.BillingModelResponse;
import com.smartstay.console.responses.bills.BillingRulesResponse;
import com.smartstay.console.responses.bills.BillingTypeResponse;
import com.smartstay.console.responses.customers.CustomerRecHistoryRes;
import com.smartstay.console.responses.customers.CustomerResponse;
import com.smartstay.console.responses.users.UserActivitiesResponse;
import com.smartstay.console.responses.users.UsersResponse;

import java.util.List;

public record HostelResponse(String hostelId,
                             String hostelName,
                             String initials,
                             String mobile,
                             String houseNo,
                             String street,
                             String landmark,
                             String city,
                             String state,
                             int country,
                             int pincode,
                             String fullAddress,
                             String mainImage,
                             boolean isTrial,
                             boolean canAddTrial,
                             boolean canAddExpandableTrial,
                             List<HostelImagesResponse> additionalImages,
                             List<AmenitiesResponse> amenities,
                             List<SharingTypeResponse> sharingBreakdown,
                             int noOfFloors,
                             int noOfRooms,
                             int noOfBeds,
                             int noOfActiveTenants,
                             int noOfBookedTenants,
                             int noOfCheckedInTenants,
                             int noOfNoticeTenants,
                             int noOfVacatedTenants,
                             int noOfTerminatedTenants,
                             List<CustomerResponse> tenantList,
                             String createdAtDate,
                             String createdAtTime,
                             OwnerInfo ownerInfo,
                             List<UsersResponse> masters,
                             List<UsersResponse> staffs,
                             List<BillingTypeResponse> billingTypes,
                             List<BillingModelResponse> billingModels,
                             BillingRulesResponse currentBillingRules,
                             List<BillingRulesResponse> billingRules,
                             EbConfig ebConfig,
                             SubscriptionResponse currentSubscription,
                             List<SubscriptionResponse> subscriptions,
                             String subscriptionStatus,
                             int renewalTimeLeftDays,
                             boolean isSubscriptionActive,
                             boolean recurringStatus,
                             List<RecurringHistoryRes> recurringHistory,
                             List<CustomerRecHistoryRes> customerRecurringHistory,
                             List<UserActivitiesResponse> activities
) {
}
