package com.smartstay.console.responses.hostels;

import java.util.List;

public record RecurringTrackerRes(String hostelId,
                                  String hostelType,
                                  String hostelName,
                                  String initials,
                                  String mobile,
                                  String emailId,
                                  String houseNo,
                                  String street,
                                  String landmark,
                                  String city,
                                  String state,
                                  int country,
                                  int pincode,
                                  String fullAddress,
                                  String mainImage,
                                  OwnerInfo ownerInfo,
                                  int activeTenantCount,
                                  int invoiceAboutToBeGeneratedCount,
                                  String billingType,
                                  Integer billingStartDay,
                                  Integer billingEndDay,
                                  String currentPeriodStartDate,
                                  String currentPeriodEndDate,
                                  String lastRecurringDate,
                                  String nextRecurringDate,
                                  boolean isSubscriptionActive,
                                  boolean recurringStatus,
                                  int currentPage,
                                  int pageSize,
                                  long totalItems,
                                  int totalPages,
                                  List<RecurringHistoryRes> recurringHistory) {
}
