package com.smartstay.console.ennum;

public enum Source {
    AGENT,
    MOCK_AGENT,
    AGENT_LOGIN,
    MOCK_AGENT_LOGIN,
    AGENT_ROLE,
    SUBSCRIPTION,
    RESET_PASSWORD,
    TENANT,
    HOSTEL,
    HOSTEL_EXPENSE,
    OWNERS,
    GENERATE_RECURRING,
    DEMO_REQUEST,
    PLANS,
    PLAN_FEATURES,
    GENERATE_CUSTOMER_RECURRING,
    BILLING_RULES,
    DEMO_REQUEST_COMMENTS
}
