package com.smartstay.console.responses.customers;

public record CustomerDetailsRes(String customerId,
                                 String hostelId,
                                 String hostelName,
                                 String firstName,
                                 String lastName,
                                 String fullName,
                                 String initials,
                                 String mobSerialNo,
                                 String mobile,
                                 String emailId,
                                 String houseNo,
                                 String street,
                                 String landMark,
                                 int pinCode,
                                 String city,
                                 String state,
                                 Long countryId,
                                 String fullAddress,
                                 String profilePic,
                                 String currentStatus,
                                 String customerBedStatus,
                                 String kycStatus,
                                 String joiningDate,
                                 String expJoiningDate,
                                 String dateOfBirth,
                                 String gender,
                                 String createdBy,
                                 String updatedBy,
                                 String createdAtDate,
                                 String createdAtTime,
                                 String updatedAtDate,
                                 String updatedAtTime) {
}
