package com.smartstay.console.responses.customers;

import com.smartstay.console.responses.hostels.OwnerInfo;

import java.util.List;

public record CustomerRecTrackerRes(String customerId,
                                    String firstName,
                                    String lastName,
                                    String fullName,
                                    String initials,
                                    String mobile,
                                    String emailId,
                                    String profilePic,
                                    String houseNo,
                                    String street,
                                    String landmark,
                                    int pincode,
                                    String city,
                                    String state,
                                    Long country,
                                    String fullAddress,
                                    String bedStatus,
                                    String currentStatus,
                                    String joiningDate,
                                    String expJoiningDate,
                                    String hostelId,
                                    String hostelType,
                                    String hostelName,
                                    String HostelInitials,
                                    String HostelMobile,
                                    String HostelEmailId,
                                    String HostelHouseNo,
                                    String HostelStreet,
                                    String HostelLandmark,
                                    String HostelCity,
                                    String HostelState,
                                    int HostelCountry,
                                    int HostelPincode,
                                    String HostelFullAddress,
                                    String mainImage,
                                    OwnerInfo ownerInfo,
                                    Integer billingStartDay,
                                    Integer billingEndDay,
                                    String billingType,
                                    String billingModel,
                                    String currentPeriodStartDate,
                                    String currentPeriodEndDate,
                                    String lastRecurringDate,
                                    String nextRecurringDate,
                                    boolean isSubscriptionActive,
                                    boolean recurringStatus,
                                    int currentPage,
                                    int pageSize,
                                    long totalItems,
                                    int totalPages,
                                    List<CustomerRecHistoryRes> recurringHistory) {
}
