package com.smartstay.console.responses.demoRequest;

import com.smartstay.console.responses.hostels.OwnerInfo;

import java.util.List;

public record DemoRequestResponse(Long requestId,
                                  String name,
                                  String emailId,
                                  String contactNo,
                                  String countryCode,
                                  String organization,
                                  Integer noOfHostels,
                                  Integer noOfTenant,
                                  String city,
                                  String state,
                                  String country,
                                  String demoRequestStatus,
                                  boolean canAssignStaff,
                                  boolean canMarkDropped,
                                  boolean isReAssignStaff,
                                  Boolean isDemoCompleted,
                                  Boolean isAssigned,
                                  String assignedToId,
                                  String assignedTo,
                                  String assignedById,
                                  String assignedBy,
                                  String presentedById,
                                  String presentedBy,
                                  String comments,
                                  String requestedDate,
                                  String requestedTime,
                                  String presentedAtDate,
                                  String presentedAtTime,
                                  String source,
                                  String parentId,
                                  boolean isOwnerDeleted,
                                  OwnerInfo owner,
                                  String demoDate,
                                  String demoDateFromTime,
                                  String demoDateToTime,
                                  String demoType,
                                  String demoMeetLink,
                                  String dropReason,
                                  String createdAtDate,
                                  String createdAtTime,
                                  List<DemoRequestCommentsResponse> demoRequestComments,
                                  List<DemoRequestActivityResponse> demoRequestActivities) {
}
