package com.smartstay.console.services;

import com.smartstay.console.dao.AdminNotifications;
import com.smartstay.console.ennum.NotificationType;
import com.smartstay.console.ennum.UserType;
import com.smartstay.console.repositories.AdminNotificationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Date;

@Service
public class NotificationService {

    @Autowired
    AdminNotificationRepository adminNotificationRepository;

    public void addAdminNotificationsForRecurringInvoice(String hostelId) {
        AdminNotifications adminNotifications = new AdminNotifications();
        adminNotifications.setNotificationType(NotificationType.RECURRING_INVOICE.name());
        adminNotifications.setUserId(null);
        adminNotifications.setHostelId(hostelId);
        adminNotifications.setSourceId(null);
        adminNotifications.setDescription("Your rental invoice has been generated by admin.");
        adminNotifications.setTitle("Recurring invoice has been generated.");
        adminNotifications.setUserType(UserType.ALL_EXCEPT_TENANT.name());
        adminNotifications.setCreatedAt(new Date());
        adminNotifications.setActive(true);
        adminNotifications.setRead(false);

        adminNotificationRepository.save(adminNotifications);
    }
}
