package com.smartstay.console.responses.transaction;

public record TransactionResponse(String transactionId,
                                  String type,
                                  Double paidAmount,
                                  String status,
                                  String invoiceId,
                                  String invoiceNumber,
                                  String invoiceType,
                                  String hostelId,
                                  String hostelName,
                                  String customerId,
                                  String customerName,
                                  String paymentDate,
                                  String paymentTime,
                                  String transactionMode,
                                  String transactionReferenceId,
                                  String receiptUrl,
                                  String bankId,
                                  String accountHolderName,
                                  String referenceNumber,
                                  String createdById,
                                  String createdBy,
                                  String updatedById,
                                  String updatedBy,
                                  String createdAtDate,
                                  String createdAtTime) {
}
